export default {
  NEWS_RECEIVED: 'NEWS_RECEIVED',
  NEWSITEM_RECEIVED: 'NEWSITEM_RECEIVED',
  NEWSITEM_LOADING: 'NEWSITEM_LOADING',
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGGEDIN: 'USER_LOGGEDIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_RECEIVED: 'USER_RECEIVED',
  ALL_USERS_RECEIVED: 'ALL_USERS_RECEIVED',
  USER_LOADING: 'USER_LOADING',
  USER_RAVEN_AUTH: "USER_RAVEN_AUTH",

  USERS_BY_SUBJECT_RECEIVED: "USERS_BY_SUBJECT_RECEIVED",
  ALL_SUBJECTS_RECEIVED: "ALL_SUBJECTS_RECEIVED",

  SUBJECT_RECEIVED: "SUBJECT_RECEIVED",
  ACCOMMODATION_RECEIVED: "ACCOMMODATION_RECEIVED",
}